server:
  port: 9000

spring:
  data:
    redis:
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
      port: 6379
      host: '${custom.redis.host}'
  transaction:
    default-timeout: '${custom.transaction.default-timeout}'
  profiles:
    active: prod
    include: secret
  datasource:
    url: '${custom.db.url}'
    username: '${custom.db.username}'
    password: '${custom.db.password}'
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: '${custom.hikari.maximum-pool-size}'
      idle-timeout: '${custom.hikari.idle-timeout}'
      max-lifetime: '${custom.hikari.max-lifetime}'
      minimum-idle: '${custom.hikari.minimum-idle}'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: Google
            scope:
              - email
              - profile

app:
  oauth2:
    authorized-redirect-uri: '${custom.oauth2.authorized-redirect-url}'

logging:
  level:
    root: INFO
    org.hibernate.orm.jdbc.bind: trace
