server:
  port: 9000
spring:
  data:
    redis:
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
      port: 6379
      host: '${custom.redis.host}'
      password: '${custom.redis.password}'
  transaction:
    default-timeout: '${custom.transaction.default-timeout}'
  profiles:
    active: prod
    include: secret
  datasource:
    url: '${custom.db.url}'
    username: '${custom.db.username}'
    password: '${custom.db.password}'
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: '${custom.hikari.maximum-pool-size}'
      idle-timeout: '${custom.hikari.idle-timeout}'
      max-lifetime: '${custom.hikari.max-lifetime}'
      minimum-idle: '${custom.hikari.minimum-idle}'
    dbcp2:
      validation-query: SELECT 1
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: false
  servlet:
    multipart:
      enabled: true
      max-request-size: 500MB
      max-file-size: 500MB
  sql:
    init:
      mode: always

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: Google
            scope:
              - email
              - profile

azure:
  storage:
    connection-string: '${azure.storage.connection-string}'
    container-name: '${azure.storage.container-name}'

iamport:
  rest:
    apiKey: '${iamport.rest.apiKey}'
    apiSecret: '${iamport.rest.apiSecret}'

logging:
  level:
    root: INFO
    org.hibernate.orm.jdbc.bind: trace


