server:
  port: 9000
spring:
  transaction:
    default-timeout: '${custom.transaction.default-timeout}'
  profiles:
    active: prod
    include: secret
  datasource:
    hikari:
      maximum-pool-size: '${custom.hikari.maximum-pool-size}'
      idle-timeout: '${custom.hikari.idle-timeout}'
    driver-class-name: org.mariadb.jdbc.Driver
    url: '${custom.db.url}'
    username: '${custom.db.username}'
    password: '${custom.db.password}'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: Google
            redirect-uri: '${custom.site.baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - email
              - profile

logging:
  level:
    root: INFO
    org.hibernate.orm.jdbc.bind: trace
